import React from 'react';

export default function DNASummary({ summary, computedAt, onRecompute, computing }) {
  return (
    <div style={styles.wrapper} className="glass">
      <div style={styles.header}>
        <div style={styles.badge}>
          <span style={styles.dot} />
          SoundDNA Summary
        </div>
        {computedAt && (
          <span style={styles.date}>
            {new Date(computedAt).toLocaleDateString()}
          </span>
        )}
      </div>

      <blockquote style={styles.summary}>
        {summary || 'Your musical fingerprint is ready.'}
      </blockquote>

      <div style={styles.footer}>
        <span style={styles.poweredBy}>✦ Generated by Claude AI</span>
        <button style={styles.recomputeBtn} onClick={onRecompute} disabled={computing}>
          {computing ? 'Recomputing...' : '↻ Refresh'}
        </button>
      </div>
    </div>
  );
}

const styles = {
  wrapper: { padding: 'var(--space-6)', height: '100%', display: 'flex', flexDirection: 'column' },
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 'var(--space-6)' },
  badge: { display: 'flex', alignItems: 'center', gap: 'var(--space-2)', color: 'var(--accent-primary)', fontFamily: 'var(--font-mono)', fontSize: '0.75rem', letterSpacing: '0.1em', textTransform: 'uppercase' },
  dot: { width: '8px', height: '8px', borderRadius: '50%', background: 'var(--accent-primary)', boxShadow: '0 0 8px var(--accent-primary)', display: 'inline-block', flexShrink: 0 },
  date: { color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: '0.7rem' },
  summary: {
    flex: 1,
    fontFamily: 'var(--font-display)',
    fontSize: '1.05rem',
    fontStyle: 'italic',
    lineHeight: 1.8,
    color: 'var(--text-primary)',
    borderLeft: '3px solid var(--accent-primary)',
    paddingLeft: 'var(--space-4)',
    marginBottom: 'var(--space-6)',
  },
  footer: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  poweredBy: { color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: '0.7rem' },
  recomputeBtn: {
    background: 'none',
    border: '1px solid var(--border)',
    color: 'var(--accent-primary)',
    fontFamily: 'var(--font-mono)',
    fontSize: '0.75rem',
    padding: '0.3rem 0.8rem',
    borderRadius: 'var(--radius-full)',
    cursor: 'pointer',
    transition: 'border-color var(--transition-fast)',
  },
};
