import React, { useEffect, useRef, useState } from 'react';
import * as d3 from 'd3';
import { useSeeds, usePlayerCtx } from '../lib';
import { FeatureBar, TrackSearchInput } from './UI';
import { FEATURE_META, describeFeature } from '../lib';

// ══════════════════════════════════════════════════════════════════════════════
// RADAR CHART
// ══════════════════════════════════════════════════════════════════════════════
export function RadarChart({ data = [], size = 300 }) {
  const svgRef = useRef(null);

  useEffect(() => {
    if (!data.length || !svgRef.current) return;
    const svg    = d3.select(svgRef.current);
    svg.selectAll('*').remove();

    const margin = 46;
    const r      = size / 2 - margin;
    const cx     = size / 2;
    const total  = data.length;
    const slice  = (Math.PI * 2) / total;
    const rScale = d3.scaleLinear().range([0, r]).domain([0, 1]);
    const g      = svg.attr('width', size).attr('height', size).append('g').attr('transform', `translate(${cx},${cx})`);

    // Glow filter
    const defs = svg.append('defs');
    const flt  = defs.append('filter').attr('id', 'glow');
    flt.append('feGaussianBlur').attr('stdDeviation', '4').attr('result', 'cb');
    const fm = flt.append('feMerge');
    fm.append('feMergeNode').attr('in', 'cb');
    fm.append('feMergeNode').attr('in', 'SourceGraphic');

    // Grid
    for (let lvl = 1; lvl <= 5; lvl++) {
      g.append('circle').attr('r', (r / 5) * lvl).attr('fill', 'none').attr('stroke', 'rgba(168,85,247,0.1)').attr('stroke-width', 1);
    }

    // Axes + labels
    data.forEach((d, i) => {
      const a  = slice * i - Math.PI / 2;
      const x  = rScale(1) * Math.cos(a);
      const y  = rScale(1) * Math.sin(a);
      const lx = (r + 22) * Math.cos(a);
      const ly = (r + 22) * Math.sin(a);
      g.append('line').attr('x1', 0).attr('y1', 0).attr('x2', x).attr('y2', y).attr('stroke', 'rgba(168,85,247,0.2)').attr('stroke-width', 1);
      g.append('text').attr('x', lx).attr('y', ly).attr('text-anchor', 'middle').attr('dominant-baseline', 'middle').attr('fill', '#9d8fc4').attr('font-size', '11px').attr('font-family', "'Syne',sans-serif").attr('font-weight', '600').text(d.axis);
    });

    // Blob
    const line = d3.lineRadial().radius((d) => rScale(d.value)).angle((_, i) => i * slice).curve(d3.curveLinearClosed);
    const blob = g.append('g');
    blob.append('path').datum(data).attr('d', line).attr('fill', 'rgba(168,85,247,0.18)').attr('stroke', 'none');
    blob.append('path').datum(data).attr('d', line).attr('fill', 'none').attr('stroke', '#a855f7').attr('stroke-width', 2).attr('filter', 'url(#glow)');

    data.forEach((d, i) => {
      const a = slice * i - Math.PI / 2;
      g.append('circle').attr('cx', rScale(d.value) * Math.cos(a)).attr('cy', rScale(d.value) * Math.sin(a)).attr('r', 4).attr('fill', '#a855f7').attr('stroke', '#f1eeff').attr('stroke-width', 1.5).attr('filter', 'url(#glow)');
    });
  }, [data, size]);

  return <div style={{ display:'flex', justifyContent:'center' }}><svg ref={svgRef} /></div>;
}

// ══════════════════════════════════════════════════════════════════════════════
// DNA SUMMARY CARD
// ══════════════════════════════════════════════════════════════════════════════
export function DNASummary({ summary, computedAt, onRecompute, computing }) {
  return (
    <div className="glass" style={{ padding:'1.5rem', display:'flex', flexDirection:'column', gap:'1rem', height:'100%' }}>
      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between' }}>
        <div style={{ display:'flex', alignItems:'center', gap:'8px', color:'var(--accent)', fontFamily:'var(--mono)', fontSize:'0.72rem', textTransform:'uppercase', letterSpacing:'0.1em' }}>
          <span style={{ width:8, height:8, borderRadius:'50%', background:'var(--accent)', boxShadow:'0 0 8px var(--accent)', display:'inline-block' }} />
          SoundDNA Summary
        </div>
        {computedAt && <span style={{ color:'var(--text-muted)', fontFamily:'var(--mono)', fontSize:'0.68rem' }}>{new Date(computedAt).toLocaleDateString()}</span>}
      </div>

      <blockquote style={{ flex:1, fontStyle:'italic', lineHeight:1.8, borderLeft:'3px solid var(--accent)', paddingLeft:'1rem', color:'var(--text-primary)', fontSize:'1rem' }}>
        {summary || 'Your musical fingerprint is ready.'}
      </blockquote>

      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between' }}>
        <span style={{ fontFamily:'var(--mono)', fontSize:'0.68rem', color:'var(--text-muted)' }}>✦ Generated by Claude AI</span>
        <button onClick={onRecompute} disabled={computing} style={{ border:'1px solid var(--border)', color:'var(--accent)', fontFamily:'var(--mono)', fontSize:'0.72rem', padding:'0.3rem 0.8rem', borderRadius:'var(--radius-full)', cursor:'pointer' }}>
          {computing ? 'Recomputing…' : '↻ Refresh'}
        </button>
      </div>
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// DNA BREAKDOWN — all 13 feature bars, collapsible
// ══════════════════════════════════════════════════════════════════════════════
export function DNABreakdown({ dnaVector }) {
  const [expanded, setExpanded] = useState(false);
  if (!dnaVector?.length) return null;
  const values = Object.fromEntries(FEATURE_META.map((m, i) => [m.key, dnaVector[i] ?? 0]));
  const visible = expanded ? FEATURE_META : FEATURE_META.slice(0, 6);

  return (
    <div>
      <h3 style={{ fontWeight:700, fontSize:'1rem', marginBottom:'1rem' }}>All 13 Dimensions</h3>
      <div style={{ display:'flex', flexDirection:'column', gap:'0.75rem' }}>
        {visible.map((meta) => <FeatureBar key={meta.key} meta={meta} value={values[meta.key]} />)}
      </div>
      <button onClick={() => setExpanded((e) => !e)} style={{ marginTop:'0.75rem', color:'var(--accent)', fontFamily:'var(--mono)', fontSize:'0.72rem', cursor:'pointer', padding:0 }}>
        {expanded ? '↑ Show less' : `↓ Show all ${FEATURE_META.length} dimensions`}
      </button>
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// SEEDS MANAGER
// ══════════════════════════════════════════════════════════════════════════════
export function SeedsManager() {
  const { seeds, seedSpotifyIds, loading, adding, addSeed, removeSeed } = useSeeds();

  const handleAdd = async (track) => {
    try { await addSeed(track.spotifyId); } catch { /* error surfaced by hook */ }
  };

  return (
    <div style={{ display:'flex', flexDirection:'column', gap:'1rem' }}>
      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between' }}>
        <div>
          <h3 style={{ fontWeight:700, fontSize:'1rem' }}>Seed Tracks</h3>
          <p style={{ color:'var(--text-secondary)', fontSize:'0.8rem' }}>Anchors for your SoundDNA. Up to 10.</p>
        </div>
        <span style={{ fontFamily:'var(--mono)', fontSize:'0.72rem', color:'var(--accent)', background:'rgba(168,85,247,0.1)', border:'1px solid var(--border-bright)', padding:'0.2rem 0.6rem', borderRadius:'var(--radius-full)' }}>
          {seeds.length} / 10
        </span>
      </div>

      <TrackSearchInput onSelect={handleAdd} seedIds={seedSpotifyIds} placeholder="Search to add a seed track…" />

      {loading ? (
        <div style={{ display:'flex', flexDirection:'column', gap:'8px' }}>
          {[1,2,3].map((i) => <div key={i} className="skeleton" style={{ height:52 }} />)}
        </div>
      ) : seeds.length === 0 ? (
        <p style={{ color:'var(--text-muted)', fontSize:'0.875rem', textAlign:'center', padding:'1.5rem 0' }}>🌱 No seeds yet — search above to add some.</p>
      ) : (
        <div style={{ display:'flex', flexDirection:'column', gap:'8px' }}>
          {seeds.map((s) => {
            const t = s.track;
            if (!t) return null;
            return (
              <div key={s.id} style={{ display:'flex', alignItems:'center', gap:'10px', padding:'10px', borderRadius:'var(--radius)', background:'var(--bg-raised)', border:'1px solid var(--border)' }}>
                {t.albumArt
                  ? <img src={t.albumArt} alt="" style={{ width:40, height:40, borderRadius:'var(--radius-sm)', objectFit:'cover', flexShrink:0 }} />
                  : <div style={{ width:40, height:40, borderRadius:'var(--radius-sm)', background:'var(--bg-overlay)', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>🎵</div>
                }
                <div style={{ flex:1, minWidth:0 }}>
                  <div style={{ fontWeight:600, fontSize:'0.875rem', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{t.title}</div>
                  <div style={{ color:'var(--text-secondary)', fontSize:'0.75rem', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{t.artist}</div>
                </div>
                <button onClick={() => removeSeed(t._id || t.id)} style={{ color:'var(--text-muted)', fontSize:'0.8rem', padding:'4px 8px', borderRadius:'var(--radius-sm)' }}>✕</button>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
